# Generated by Django 3.2.20 on 2023-07-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('building', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('organization_form', models.PositiveSmallIntegerField(choices=[(0, 'Фабрика'), (1, 'Редактор'), (2, 'Индивидуальный предприниматель')], verbose_name='Форма организации')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProviderOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Задолженность')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='orgs.organization')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='orgs.organization')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='products',
            field=models.ManyToManyField(to='orgs.Product'),
        ),
    ]
