# Generated by Django 3.2.20 on 2023-07-21 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_form',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], verbose_name='Форма организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='products',
            field=models.ManyToManyField(to='orgs.Product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='providerorganization',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='orgs.organization', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='providerorganization',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_to', to='orgs.organization', verbose_name='Заказчик'),
        ),
    ]
