# Generated by Django 3.2.20 on 2023-07-21 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_auto_20230721_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerorganization',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Задолженность'),
        ),
        migrations.AlterField(
            model_name='providerorganization',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_to', to='orgs.organization', verbose_name='Заказчик'),
        ),
    ]
